name: EnderSync
version: 5.0.0
author: EnderSuite Team
main: com.endersuite.endersync.Bootstrap
softdepend: [Vault]
loadafter: [Vault]

commands:
  endersync:
    description: The main EnderSync command.
    usage: /endersync
  es:
    description: An alias of the /endersync command.
    usage: /es